name: Build Electron App

on:
  workflow_dispatch: # 手动触发工作流的配置

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install
    
    - name: Rebuild
      run: npm run rebuild

    - name: Build- Render
      run: npm run build

    - name: Release Win
      run: npm run release:win

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-app
        path: path/to/your/app # 替换为你的打包输出目录
